---
servers:
  #- name: DC1-SW1
  #  adapters:
  #    - endpoint_ports: [ Ethernet1 ]
  #      switch_ports: [ Ethernet3 ]
  #      switches: [ DC1-CL1 ]
  #      port_channel:
  #        description: PortChannel_DC1-SW1
  #        mode: active

  
  # - name: host3
  #   adapters:
  #     - endpoint_ports: [ Ethernet1, Ethernet2 ]
  #       switch_ports: [ Ethernet7, Ethernet7 ]
  #       switches: [ leaf3, leaf4 ]
  #       vlans: 20
  #       mode: access
  #       spanning_tree_portfast: edge
  #       port_channel:
  #         description: PortChannel host3
  #         mode: active