---
tenants:
  - name: TENANT_C1
    vrfs:
      - name: VRF_A
        vrf_id: 10
        address_families:
          - vpn-ipv4
        svis:
          - id: 10
            name: DMZ
            enabled: true
            ip_address_virtual: 10.1.10.1/24
          - id: 20
            name: DMZ
            enabled: true
            ip_address_virtual: 10.1.20.1/24
        # l3_interfaces:
        #   - interfaces: [Port-Channel100.10]
        #     ip_addresses: [10.1.5.1/24]
        #     nodes: [DC1-CL1]
        #     enabled: True 
        # bgp_peers:
        #   - ip_address: 10.1.5.254
        #     remote_as: 1
        #     nodes: [leaf4]
