---
tenants:
  - name: TENANT_C1
    mac_vrf_vni_base: 10000
    vrfs:
      - name: VRF_A
        vrf_vni: 10
        vtep_diagnostic:
          loopback: 666
          loopback_ip_range: 169.254.255.0/24
        svis:
          - id: 10
            name: DMZ
            enabled: true
            ip_address_virtual: 10.1.10.1/24
          - id: 20
            name: DMZ
            enabled: true
            ip_address_virtual: 10.1.20.1/24
        # l3_interfaces:
        #   - interfaces: [Port-Channel100.10]
        #     ip_addresses: [10.1.5.1/24]
        #     nodes: [DC1-CL1]
        #     enabled: True 
        # bgp_peers:
        #   - ip_address: 10.1.5.254
        #     remote_as: 1
        #     nodes: [leaf4]
        # static_routes:
        #   - destination_address_prefix: 0.0.0.0/0
        #     gateway: 10.10.70.10
        #     nodes: [DC1-BL1, DC1-BL2]
