---
fabric_name: DC1_FABRIC

# Set Design Type to l3ls-evpn
design:
  type: l3ls-evpn


# isis underlay defaults
underlay_routing_protocol: isis
isis_advertise_passive_only: true
isis_area_id: "49.0001"
isis_default_circuit_type: "level-2"
isis_default_is_type: "level-2"
isis_maximum_paths: 128

overlay_routing_protocol: ibgp

custom_structured_configuration_switchport_default:
  mode: routed

# Spine Switches
spine:
  defaults:
    platform: cEOS
    loopback_ipv4_pool: 10.250.1.0/24
    isis_system_id_prefix: "1921.6810"
    bgp_as: 65100
  nodes:
    - name: DC1-SP1
      id: 10
      mgmt_interface: Management1
      mgmt_ip: 10.88.169.131/24
    - name: DC1-SP2
      id: 11
      mgmt_interface: Management1
      mgmt_ip: 10.88.169.132/24

# Leaf Switches
l3leaf:
  defaults:
    platform: cEOS
    spanning_tree_priority: 4096
    spanning_tree_mode: mstp
    loopback_ipv4_pool: 10.250.1.0/24
    loopback_ipv4_offset: 2
    isis_system_id_prefix: "1921.6810"
    vtep_loopback_ipv4_pool: 10.255.1.0/24
    uplink_switches: [ DC1-SP1, DC1-SP2 ]
    uplink_interfaces: [ Ethernet1, Ethernet2 ]
    uplink_ipv4_pool: 172.16.1.0/24
    mlag_interfaces: [ Ethernet8 ]
    mlag_peer_ipv4_pool: 10.251.1.0/24
    mlag_peer_l3_ipv4_pool: 10.252.1.0/24
    virtual_router_mac_address: 00:1c:73:00:00:99
  node_groups:
    - group: DC1_RACK1
      bgp_as: 65100
      nodes:
        - name: DC1-CL1
          id: 1
          mgmt_interface: Management1
          mgmt_ip: 10.88.169.135/24
          uplink_switch_interfaces: [ Ethernet1, Ethernet1 ]
        - name: DC1-CL2
          id: 2
          mgmt_interface: Management1
          mgmt_ip: 10.88.169.136/24
          uplink_switch_interfaces: [ Ethernet2, Ethernet2 ]
    - group: DC1_RACK2
      bgp_as: 65100
      nodes:
        - name: DC1-CL3
          id: 3
          mgmt_interface: Management1
          mgmt_ip: 10.88.169.137/24
          uplink_switch_interfaces: [ Ethernet3, Ethernet3 ]
        - name: DC1-CL4
          id: 4
          mgmt_interface: Management1
          mgmt_ip: 10.88.169.138/24
          uplink_switch_interfaces: [ Ethernet4, Ethernet4 ]
    - group: DC1_BL
      bgp_as: 65100
      evpn_gateway:
         evpn_l2:
           enabled: true
         evpn_l3:
           enabled: true
           inter_domain: true
      nodes:
        - name: DC1-BL1
          id: 5
          mgmt_interface: Management1
          mgmt_ip: 10.88.169.133/24
          uplink_switch_interfaces: [ Ethernet5, Ethernet5 ]
          evpn_gateway:
             remote_peers:
               - hostname: DC2-BL1
                 bgp_as: 65200
                 ip_address: 10.250.2.7
        - name: DC1-BL2
          id: 6
          mgmt_interface: Management1
          mgmt_ip: 10.88.169.134/24
          uplink_switch_interfaces: [ Ethernet6, Ethernet6 ]
          evpn_gateway:
             remote_peers:
               - hostname: DC2-BL2
                 bgp_as: 65200
                 ip_address: 10.250.2.8