---
- name: Playbook for uploading configlets to CloudVision
  hosts: cvp1
  vars_files:
    - ../vars/CVP_model.yml
  tasks:
    - name: Upload configlets
      arista.cvp.cv_configlet_v3:
        configlets: "{{ CVP_CONFIGLETS }}"
        state: present
        apply_mode: loose
      register: CVP_CHANGE
    - name: Run tasks from previous task
      arista.cvp.cv_task_v3:
        tasks: "{{ CVP_CHANGE.taskIds }}"